name: General Question
description: Asks a general question
title: "[Question] "
labels: [ "question", "state: pending" ]
body:
  - type: markdown
    attributes:
      value: |-
        Please join the [Discord Server](https://discord.negative.games) for questions or ask them in [our Discussions](https://github.com/Negative-Games/Framework/discussions).
        
        Keep in mind that this isn't the place to learn Java.  
        Please head over to [StackOverflow](https://stackoverflow.com/questions/tagged/java) for your general programming questions.
  - type: checkboxes
    attributes:
      label: General Troubleshooting
      description: You confirm to have made the following checks first.
      options:
        - label: I have checked for similar issues on the Issue-tracker.
          required: true
  - type: textarea
    attributes:
      label: "Question"
      description: "Provide a small description of what you would like to ask!."
      placeholder: "I was wondering if..."
    validations:
      required: true